# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/knn-spatial-boost',
                'doc_host': 'https://cl3t0.github.io',
                'git_url': 'https://github.com/cl3t0/knn-spatial-boost',
                'lib_path': 'knn_spatial_boost'},
  'syms': { 'knn_spatial_boost.core': { 'knn_spatial_boost.core.KNNSpatialBooster': ( 'core.html#knnspatialbooster',
                                                                                      'knn_spatial_boost/core.py'),
                                        'knn_spatial_boost.core.KNNSpatialBooster.fit': ( 'core.html#knnspatialbooster.fit',
                                                                                          'knn_spatial_boost/core.py'),
                                        'knn_spatial_boost.core.KNNSpatialBooster.knn_enrichment': ( 'core.html#knnspatialbooster.knn_enrichment',
                                                                                                     'knn_spatial_boost/core.py'),
                                        'knn_spatial_boost.core.KNNSpatialBooster.predict': ( 'core.html#knnspatialbooster.predict',
                                                                                              'knn_spatial_boost/core.py'),
                                        'knn_spatial_boost.core.KNNSpatialBooster.score': ( 'core.html#knnspatialbooster.score',
                                                                                            'knn_spatial_boost/core.py')},
            'knn_spatial_boost.model': {}}}
