# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/knn-spatial-boost',
                'doc_host': 'https://cl3t0.github.io',
                'git_url': 'https://github.com/cl3t0/knn-spatial-boost',
                'lib_path': 'knn_spatial_boost'},
  'syms': {'knn_spatial_boost.core': {'knn_spatial_boost.core.foo': ('core.html#foo', 'knn_spatial_boost/core.py')}}}
